# Generated by Django 6.0.3 on 2026-05-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='date',
        ),
    ]
