# Generated by Django 6.0.4 on 2026-05-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0002_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='balance',
        ),
    ]
