# Generated by Django 6.0.4 on 2026-05-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0002_remove_supplier_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
