# Generated by Django 6.0.4 on 2026-05-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0003_alter_supplier_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deposit',
            name='glass_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
