# Generated by Django 6.0.4 on 2026-05-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0003_remove_deposit_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='supplier',
        ),
    ]
