# Generated by Django 6.0.4 on 2026-05-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0003_alter_deposit_phone_alter_register_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='specification',
        ),
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.CharField(default='building_materials', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='payment_method',
            field=models.CharField(default='building_materials', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
