# Generated by Django 6.0.4 on 2026-05-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0004_deposit_balance_deposit_glass_type_deposit_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('amount_paid', models.FloatField(default=0)),
                ('balance', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
