# Generated by Django 6.0.4 on 2026-05-07 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0004_remove_stock_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='purpose',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='deposit',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='nin',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
