# Generated by Django 6.0.4 on 2026-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0005_rename_purpose_deposit_item_name_deposit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='nin',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
