# Generated by Django 6.0.4 on 2026-05-13 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0005_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount_paid',
            field=models.FloatField(),
        ),
    ]
