# Generated by Django 6.0.4 on 2026-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0006_alter_deposit_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
