# Generated by Django 6.0.4 on 2026-05-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0006_credit_created_at_credit_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='credit',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='credit',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
