# Generated by Django 6.0.4 on 2026-05-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0007_remove_credit_quantity_alter_credit_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
