# Generated by Django 6.0.4 on 2026-05-08 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0007_alter_deposit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
