# Generated by Django 6.0.4 on 2026-05-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0008_credit_quantity_alter_credit_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='credit',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='credit',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hardwareapp.credit')),
            ],
        ),
    ]
