# Generated by Django 6.0.4 on 2026-05-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0009_alter_deposit_date_alter_receipt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
