# Generated by Django 6.0.4 on 2026-05-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0010_credit_updated_at_alter_credit_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
