# Generated by Django 6.0.4 on 2026-05-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0011_sale_distance_sale_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='transport',
            field=models.FloatField(default=0),
        ),
    ]
