# Generated by Django 6.0.4 on 2026-05-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0011_rename_date_deposit_created_at_remove_receipt_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
