# Generated by Django 6.0.4 on 2026-05-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0013_alter_credit_amount_paid_alter_credit_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='distance',
            new_name='distance_km',
        ),
    ]
