# Generated by Django 6.0.4 on 2026-05-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0013_sale_date_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_at',
        ),
    ]
