# Generated by Django 6.0.4 on 2026-05-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0014_rename_distance_sale_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='unit_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
