# Generated by Django 6.0.4 on 2026-05-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0015_alter_deposit_amount_alter_deposit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='supplier',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(max_length=14),
        ),
    ]
