# Generated by Django 6.0.4 on 2026-05-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0016_remove_deposit_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='unit_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
