# Generated by Django 6.0.4 on 2026-05-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0017_deposit_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='unit_price',
        ),
    ]
