# Generated by Django 6.0.4 on 2026-05-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0019_saleitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
