# Generated by Django 6.0.4 on 2026-05-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0022_delete_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
